# Default values for template-node-typescript.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global: {}

replicaCount: 1
logLevel: "debug"

image:
  repository: replace
  tag: replace
  pullPolicy: IfNotPresent
  port: 8080
  productcatalogserviceaddr: "productcatalogservice:3550"
  currencyserviceaddr: "currencyservice:7000"
  cartserviceaddr: "cartservice:7070"
  recommendationserviceaddr: "recommendationservice:8080"
  shippingserviceaddr: "shippingservice:50051"
  checkoutserviceaddr: "checkoutservice:5050"
  adserviceaddr: "adservice:9555"

nameOverride: ""
fullnameOverride: ""

service:
  enabled: false
  type: ClusterIP
  port: 8080

route:
  enabled: false

ingress:
  enabled: true
  appid:
    enabled: false
    # web or app - https://cloud.ibm.com/docs/services/appid?topic=appid-kube-auth
    requestType: web

  #  host: hello
  namespaceInHost: true
  subdomain: containers.appdomain.cloud
  path: "/"

#  tlsSecretName: ""

jaegerConfigName: jaeger-config
jaegerSecretName: jaeger-access

vcsInfo:
  repoUrl: ""
  branch: ""

partOf: multicloud-demo

runtime: golang

serviceMesh:
  sidecar: true
